package com.rd.logic.greendao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.rd.logic.greendao.entity.GestureBean;
import com.rd.logic.greendao.entity.RegionBean;

import com.rd.logic.greendao.dao.GestureBeanDao;
import com.rd.logic.greendao.dao.RegionBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig gestureBeanDaoConfig;
    private final DaoConfig regionBeanDaoConfig;

    private final GestureBeanDao gestureBeanDao;
    private final RegionBeanDao regionBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        gestureBeanDaoConfig = daoConfigMap.get(GestureBeanDao.class).clone();
        gestureBeanDaoConfig.initIdentityScope(type);

        regionBeanDaoConfig = daoConfigMap.get(RegionBeanDao.class).clone();
        regionBeanDaoConfig.initIdentityScope(type);

        gestureBeanDao = new GestureBeanDao(gestureBeanDaoConfig, this);
        regionBeanDao = new RegionBeanDao(regionBeanDaoConfig, this);

        registerDao(GestureBean.class, gestureBeanDao);
        registerDao(RegionBean.class, regionBeanDao);
    }
    
    public void clear() {
        gestureBeanDaoConfig.clearIdentityScope();
        regionBeanDaoConfig.clearIdentityScope();
    }

    public GestureBeanDao getGestureBeanDao() {
        return gestureBeanDao;
    }

    public RegionBeanDao getRegionBeanDao() {
        return regionBeanDao;
    }

}
